// tester configs
export const SET_DATA_SOURCE = "SET_DATA_SOURCE";
export const SET_LOCAL_CSV = "SET_LOCAL_CSV";
export const SET_MY_REST_API_URL = "SET_MY_REST_API_URL";
export const SET_SYMBOL = "SET_SYMBOL";
export const SET_PERIOD = "SET_PERIOD";
export const SET_IS_DEFAULT = "SET_IS_DEFAULT";
export const SET_STRATEGY = "SET_STRATEGY";
export const ADD_CANDLES = "ADD_CANDLES";
export const SET_MARGIN_TO_BALANCE_PERCENT = "SET_MARGIN_TO_BALANCE_PERCENT";
export const SET_DAYTIME_SPREAD = "SET_DAYTIME_SPREAD";
export const SET_NIGHTTIME_SPREAD = "SET_NIGHTTIME_SPREAD";
export const SET_LOT_SIZE = "SET_LOT_SIZE";

// data source configs
export const SET_CURRENCY_PRICE = "SET_CURRENCY_PRICE";
export const SET_LEVERAGE = "SET_LEVERAGE";
export const SET_NOMINAL_VALUE = "SET_NOMINAL_VALUE";
export const SET_INIT_BALANCE = "SET_INIT_BALANCE";

// tester results
export const SET_IS_TEST_FINISHED = "SET_IS_TEST_FINISHED";
export const SET_TRADES = "SET_TRADES";
export const SET_END_BALANCE = "SET_END_BALANCE";
export const SET_CHART_MAIN_CANDLES = "SET_CHART_MAIN_CANDLES";
export const SET_FINISHED_REASON = "SET_FINISHED_REASON";